@startuml smoke-login

|Cliente|
start

:Acessa a tela de login;
:Informa e-mail e senha;
:Envia formulário;

|Sistema|
:Valida dados de acesso;

if (Dados válidos?) then (Sim)
    :Autentica cliente;
    :Libera acesso à área do cliente;

    |Cliente|
    :Acessa área do cliente;
else (Não)
    :Exibe mensagem de erro;

    |Cliente|
    :Visualiza mensagem de erro;
endif

stop

@enduml
