@startuml top-down

component "Pedido" as Pedido

component "Calculadora de Frete" as Frete
component "Pagamento Stub" as PagamentoStub
component "Estoque Stub" as EstoqueStub
component "Entrega Stub" as EntregaStub

component "Pagamento" as Pagamento
component "Estoque" as Estoque
component "Entrega" as Entrega

Pedido --> Frete
Pedido --> PagamentoStub
Pedido --> EstoqueStub
Pedido --> EntregaStub

PagamentoStub ..> Pagamento : substitui
EstoqueStub ..> Estoque : substitui
EntregaStub ..> Entrega : substitui

@enduml
