@startuml unidade

class Pedido {
    - valorTotal: double
    - pesoTotal: double
}

interface ConsultaFrete {
    + valorBaseCEP(cep: String): double
}

class ConsultaFreteStub {
    + valorBaseCEP(cep: String): double
}

class CalculadoraFrete {
    - consultaFrete: ConsultaFrete
    + calculaFrete(pedido: Pedido, cep: String): double
}

class CalculadoraFreteTest {
    + calculaFretePorPeso()
    + freteGratis()
}

CalculadoraFreteTest ..> CalculadoraFrete : testa
CalculadoraFrete --> Pedido : utiliza
CalculadoraFrete --> ConsultaFrete : consulta
ConsultaFreteStub ..|> ConsultaFrete : implementa

@enduml

