@startuml unidade

class Pedido {
    - valorTotal: double
    - pesoTotal: double
}

class EnderecoEntrega {
    - cep: String
}

class CalculadoraFrete {
    + calculaFrete(pedido: Pedido, endereco: EnderecoEntrega): double
}

class CalculadoraFreteTest {
    + calculaFretePorPeso()
    + freteGratis()
}

CalculadoraFreteTest ..> CalculadoraFrete : testa
CalculadoraFrete --> Pedido : utiliza
CalculadoraFrete --> EnderecoEntrega : utiliza

@enduml
